inserts new row in the database for each new comment and answer
kartverket/regelrett pull request #186
Opened 2024-08-29 13:17 UTC by malinnsnieske

## Background
Legge til ny rad i databasen for å kunne ha historikk på svarene og kommentarene

## Solution
Endret slik at raden i databasen ikke blir erstattet, men ny legges heller til

Resolves #issue-this-pr-resolves
#149 
#150

2024-08-30 10:03 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
> +                if (resultSet.next()) insertAnswerRow(conn, answer)
Ta bort `if`, tolker det som at hvis du skal legge til det første svaret så skjer ingenting fordi da er resultSet.next() === false og inget skjer.

2024-08-30 10:03 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
> +                if (resultSet.next()) insertCommentRow(conn, comment)
Samme her ingen `if`

2024-08-30 10:03 UTC, perzonas requested changes
Ta bort if statements og bare kjør inserts

2024-09-02 11:05 UTC, andersstandal approved these changes
Ser nais ut det her 🚀

2024-09-02 11:06 UTC, perzonas approved these changes

2024-09-02 11:18 UTC, merged