separate answer and comments from table
kartverket/regelrett pull request #250
Opened 2024-09-16 12:39 UTC by malinnsnieske

## Background
Kommentarer og svar fetches sammen med tabellen i frontend. Dette gjør det er vanskelig med caching og oppdatering av states.

## Solution
Kommentarer og svar blir ikke returnert når tabellen fetches. I stedet må egne endepunkter brukes. Dataen settes deretter sammen når tabellen skal vises.
@perzonas er det noe jeg ikke gjorde som du hadde tenkt at skulle gjøres i denne ticketen?

Resolves #issue-this-pr-resolves
#243

2024-09-18 08:25 UTC, andersstandal approved these changes
Synes dette ser ganske så nice ut 🚀

2024-09-18 10:36 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
@andersstandal Dette filnavnet føles lit utdatert, jeg vet ikke ens hva det er for noe...
Er et bedre navn AirtableResponseMapper eller noe?

2024-09-18 10:38 UTC, perzonas commented on frontend/beCompliant/src/api/types.ts
> +  comments?: Comment[];
hvorfor blev disse potentiellt undefined?

2024-09-18 10:45 UTC, perzonas commented on frontend/beCompliant/src/hooks/useSubmitAnswers.ts
> +        queryKey: [PATH_ANSWERS, team],
hente fra apiConfig?

2024-09-18 10:47 UTC, perzonas commented on frontend/beCompliant/src/hooks/useSubmitAnswers.ts
> +        queryKey: [PATH_ANSWERS, team],
team ? apiConfig.answer.withTeam.queryKey(team) : apiConfig.answer.queryKey

2024-09-18 10:50 UTC, perzonas commented on frontend/beCompliant/src/pages/ActivityPage.tsx
> +  );
Skape en egen fil eller finn en utils fil og dytte disse funktionerne in i den, det gjører det mulig at skrive testing for disse i fremtiden og gjører komponenten letter at læsa

2024-09-18 10:52 UTC, perzonas commented on frontend/beCompliant/src/api/types.ts
> +  comments?: Comment[];
Du skal kunne slette spørsmål tegnet her

2024-09-18 10:53 UTC, perzonas commented on frontend/beCompliant/src/components/Table.tsx
> +    accessorFn: (row: Question) => row.comments?.at(-1)?.comment ?? '',
ta bort sprøsmåltegnet se kommentaren ovan ☝️

2024-09-18 10:53 UTC, perzonas commented on frontend/beCompliant/src/components/table/TableCell.tsx
> +        updated={row.original.answers?.[0]?.updated}
ta bort sprøsmåltegnet se kommentaren ovan ☝️

2024-09-18 10:53 UTC, perzonas commented on frontend/beCompliant/src/components/table/TableStatistics.tsx
> +    if (data.answers?.[0]?.answer) {
same

2024-09-18 10:54 UTC, perzonas commented on frontend/beCompliant/src/api/types.ts
> +  comments?: Comment[];
Hvis den klager på dette kan  kan vi se på det sammen

2024-09-18 10:59 UTC, perzonas commented on frontend/beCompliant/src/pages/ActivityPage.tsx
> +  }));
Potentiellt at denne kan dyttes ut i egen fil som en egen mapper til trots at den er ganske simpel

2024-09-18 11:00 UTC, perzonas requested changes
Veldig mye bra her! Lit små pirk fra min side bare

2024-09-18 11:57 UTC, andersstandal commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
Ja, har alltid lurt på hva et metodeverk er for noe

2024-09-19 07:22 UTC, perzonas commented on frontend/beCompliant/src/utils/answerCommentMapper.ts
Noe bedre navn a la mapperUtil

2024-09-19 07:30 UTC, perzonas commented on frontend/beCompliant/src/utils/answerCommentMapper.ts
> +  tableData.records = tableData.records.map((question) => ({
Hade tenkt at du returnerer verdien her og ikke populerer records  i tillegg. 
```suggestion
  return tableData.records.map((question) => ({
```

2024-09-19 07:31 UTC, perzonas commented on frontend/beCompliant/src/utils/answerCommentMapper.ts
> +export const addCommentsAndAnswersToRecords = (
```suggestion
export const mapTableDataRecords = (
```

2024-09-19 07:32 UTC, perzonas commented on frontend/beCompliant/src/utils/answerCommentMapper.ts
> +  return tableData;
Denne kan nok slettes hvis du gjører endringerne over

2024-09-19 07:35 UTC, perzonas commented on frontend/beCompliant/src/utils/answerCommentMapper.ts
> +  tableData.records = tableData.records.map((question) => ({
Anlednignen til det er for at underlette testing og ha bedre struktur. Nå gjører denne funktionen 1 ting mapper, innen gjorde den 2 ting.

Er en bra ting at tenke på at hver hjelpe funktion bare gjører en ting. Da er det enkelt at teste og enkelt at lese

2024-09-19 07:35 UTC, perzonas approved these changes
Se kommentarer, men veldig bra jobba Malin! Blir bra dette 🎉

2024-09-19 08:23 UTC, perzonas requested changes
Vi gjører fortsatt mange checks på "Svar" i koden som har blitt endret i denne PR:en må endre alle disse instanser til 'answer'

2024-09-24 09:05 UTC, closed without merging