Percent and time answer options
kartverket/regelrett pull request #305
Opened 2024-10-01 10:05 UTC by starheim98

## Background

## Solution

Resolves #issue-this-pr-resolves

2024-10-03 06:38 UTC, starheim98 commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +      ...(answerUnit != null && { answerUnit }),
Kom ikke rundt denne løsningen:
...(answerUnit != null && { answerUnit }),

har du noen tips? 😇  @perzonas

2024-10-03 07:51 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +      ...(answerUnit != null && { answerUnit }),
`answerUnit: answerUnit` tror jeg skal fungere her 😸

2024-10-03 07:56 UTC, malinnsnieske commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +        <Stack spacing={2} direction="row">
Bare et forslag: Kanskje dra denne og den for tid i egne komponenter? Så blir denne filen mindre og mer oversiktlig, og de kan gjenbrukes i f.eks. spørsmålssiden

2024-10-03 08:31 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +        <Stack spacing={2} direction="row">
støtter det

2024-10-03 08:32 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +          <InputGroup>
denne burde kanske. ha samme width som `time` for consistency

2024-10-03 08:34 UTC, perzonas commented on frontend/beCompliant/src/api/types.ts
> -  quesiton: string;
denne var ubrukt?

2024-10-03 08:35 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +  const [answerUnit, setAnswerUnit] = useState<string | null>(unit);
denne kan du ha som undefined og ikke null

2024-10-03 08:35 UTC, perzonas commented on frontend/beCompliant/src/api/types.ts
> +  answerUnit: string | null;
```suggestion
  answerUnit?: string
```

2024-10-03 08:36 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +  unit: string | null;
```suggestion
  unit?: string;
```

2024-10-03 08:39 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +    ) {
dette blir lit rart uten noen form for feedback til brukeren om hvorfor ting ikke fungerer

2024-10-03 08:40 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +    }
samme her

2024-10-03 08:41 UTC, perzonas commented on frontend/beCompliant/src/components/table/AnswerCell.tsx
> +      ...(answerUnit != null && { answerUnit }),
sammen med endringerne jeg skrevet om lenger opp med typingen

2024-10-03 08:46 UTC, perzonas commented on frontend/beCompliant/src/components/table/TableCell.tsx
> +        unit={row.original.answers.at(-1)?.answerUnit ?? null}
```suggestion
        unit={row.original.answers.at(-1)?.answerUnit}
```

2024-10-03 08:53 UTC, perzonas requested changes
lit med typingen og flytte lit kode in i egne komponenter

2024-10-10 08:03 UTC, malinnsnieske approved these changes
🚀

2024-10-10 08:06 UTC, merged