262 fix design question page
kartverket/regelrett pull request #322
Opened 2024-10-04 08:39 UTC by malinnsnieske

## Background

## Solution
De første elementene på spørsmålssiden ligner nå på skissene
Tar hensyn til svartype - foreløpig tekst og select single
La til tilbakeknapp

Resolves #issue-this-pr-resolves
#262 

https://github.com/user-attachments/assets/358d5ef9-8969-417f-b580-28069422da8b

https://github.com/user-attachments/assets/293674f3-36fb-4cf3-9b5d-20193858313a

2024-10-07 08:38 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
> +    <Stack marginBottom="120px" gap="4px">
```suggestion
    <Stack marginBottom="30" gap="1">
```

2024-10-07 08:39 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
> +    <Stack marginBottom="120px" gap="4px">
hvorfor er det sån stor marginBottom?

2024-10-07 08:39 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
> +      <Text fontSize="md">{question.id}</Text>
er ikke "md" default?

2024-10-07 08:44 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
> +          onChange={handleTextAreaAnswer}
Er det ikke mulig at bare bruker setAnswerInput her?
```suggestion
          onChange={setAnswerInput}
```

2024-10-07 08:46 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
> +          onBlur={submitTextAnswer}
Er tanken at den skal sendes på onBlur? Er det riktig behaviour?

2024-10-07 08:49 UTC, malinnsnieske commented on frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
> +          onBlur={submitTextAnswer}
Magnus ville at tekstboksen alltid skulle være i redigeringsmode så tenkte at svaret da må lagres når man trykker seg ut av boksen for å ikke lagre halvferdige svar. Eller blir det feil?

2024-10-07 08:53 UTC, perzonas commented on frontend/beCompliant/src/components/questionPage/QuestionDetails.tsx
> +    <Stack marginBottom="120px" gap="4px">
Jeg hade flyttet denne marginen ut til parent containern, denne componenten kanske ikke skal ha 120px margin alltid. Jeg hade brukt  Props  extends StackProps og siden hatt `...rest`
```suggestion
    <Stack gap="4px" {...rest}>
```

2024-10-07 08:54 UTC, perzonas commented on frontend/beCompliant/src/pages/QuestionPage.tsx
> +        />
Ref min kommentar på `QuestionDetails`

```suggestion
        <QuestionDetails
          question={question}
          answerUpdated={answers.at(-1)?.updated.toString() ?? ''}
          marginBottom='30'
        />
```

2024-10-07 08:58 UTC, perzonas requested changes
Se kommentarer

2024-10-07 12:54 UTC, malinnsnieske commented on frontend/beCompliant/src/components/questionPage/TextAreaAnswer.tsx
> +          onChange={handleTextAreaAnswer}
Den klaget på typen hmm

2024-10-07 12:55 UTC, malinnsnieske commented on frontend/beCompliant/src/pages/QuestionPage.tsx
> +        />
Blir bare 30px når jeg setter inn 30, vet du hvorfor?

2024-10-08 11:23 UTC, chribjel approved these changes

2024-10-08 11:26 UTC, merged