Internal backend data model
kartverket/regelrett pull request #82
Opened 2024-07-10 13:42 UTC by KrisAesoey

## Background

Currently, we are pretty much funneling the data we get from the AirTable API directly to the frontend, and let it handle the data handling. We need an internal model in the backend that we map the AirTable data to, if we want to be have better control of the modelling we serve to the frontend.

## Solution

This is a suggestion on how we can model the internal data. It is not complete, or implemented in the frontend, but it is a suggestion on how we can model the internal data. It still remains to fetch it in the frontend, and use the new models for submitting data to the databases.

* Added a couple new dependencies that allow us to serialize data classes, so that we don't have to covert them into JsonElements as a part of the response call.
* Created a TableController, that serves as the provider of data for the new routes. I renamed the`AirTableController` to `Service` instead in the process. I haven't worked with the Ktor paradigm before, but I'm used to Controller's being resources that the application _provides_ through its endpoints, while _services_ fetches data from other systems (like AirTable).
* Refactored the data classes used in the database, as they should be reevaluated if they fit with our new internal model.
* Created new data classes to represent answers, comments, columns, questions and tables. Tried to strip away any AirTable data not considered completely necessary. The idea is that the `Table` type is what is returned from the endpoint.

## Testing

Run the backend and use a browser (or Postman like applications), and fetch `http://localhost:8080/airtable/tblLZbUqA0XnUgC2v?team={teamName}`

2024-07-10 13:43 UTC, KrisAesoey commented on backend/build.gradle.kts
> +    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
Vi har allerede en dependency for serialization av json, men vet ikke hva den gjør annerledes

2024-07-10 13:44 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/database/DatabaseRepository.kt
>  import no.bekk.configuration.getDatabaseConnection
I denne filen er det bare datatypene på Answer og Comment som har endret navn

2024-07-10 13:46 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +        )
Dette betyr i praksis at det alltid blir sendt med et svar og en comment per spørsmål, men at feltene er "tomme" hvis det ikke er noe. Kanskje bedre med å sende null på hele objektet?

2024-07-10 13:47 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/model/internal/Column.kt
> +)
Dette er altså en kolonne i en rad, og er helt generisk siden det kan være string, int eller liste av de som er verdien.

2024-07-10 13:47 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/model/internal/Answer.kt
> +)
I database klassen har man også `question`, men vet ikke helt hva slags verdi det gir?

2024-07-10 14:18 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +        )
Tenker at null kan vare det bedre alternativet

2024-07-10 14:21 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/plugins/Routing.kt
> +    }
Støtter det, har tenkt det samme

2024-07-10 14:23 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +        )
Enig^

2024-07-10 14:26 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/model/internal/Answer.kt
> +)
Lurer på om tanken var for versjonering, at man skal kunne se tidligere svar. Fordi man ønsker å vise hva spørsmålet var når man svarte Spørsmål kan endres ved for eksempel rettskriving, men skal egentlig ikke endres hvis det er større endringer. Men det kan være fint å ha med spørsmålsteksten på grunn av det tror jeg.

2024-07-11 13:05 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +            optionalFields = metadataFields.filterNot { it.name == "Svar" }.map {
Samme her, ikke en fan av å måtte filtrere på "Svar" kolonna. Var dette eg håpte vi skulle klare å jobbe oss vekk fra somehow

2024-07-11 13:06 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/model/airtable/AirtableMapping.kt
> +        "singleLineText" -> OptionalFieldType.TEXT
Søker tips til denne typen mapping av AirTable typene ✌️

2024-07-11 13:42 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +        }
Legge inn i description i Airtable. Typ Description: "${isAnswer} For at server skal vite at dette er svar kolonnen."

2024-07-11 13:44 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +            optionalFields = metadataFields.filterNot { it.name == "Svar" }.map {
Samme som over

2024-07-11 14:09 UTC, SondreKanstad requested changes
For en PR! Pen på både innsiden og utsiden 💅 ![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbXg0M2NqMGRseDB4ejJrcTdpMGY4azc1ZWx4djZzcWw0eGJ2bWV0YiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/X9RBixlR36Uco/giphy.gif)

2024-07-11 14:09 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +        }
I en hjelpefunksjon eller lignende

2024-07-11 14:09 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/model/internal/Question.kt
> +    val comments: List<Comment>? = null,
Hvorfor er comments nullable og ikke answers?

2024-07-11 14:09 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/model/internal/Table.kt
> +    val records: List<Question>,
Mulig man skulle hatt tablemetadata som sier noe om antall kolonner, navn på kolonner, antall rader 🤔

2024-07-12 07:54 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/model/internal/Question.kt
> +    val comments: List<Comment>? = null,
Egentlig mest fordi databasen er bygget slik. I følge database funksjonene så vil man alltid få ut en liste for answers, men det samme gjelder ikke for comments! Kan godt endres på 😄

2024-07-12 07:54 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/model/internal/Table.kt
> +    val records: List<Question>,
Ja enig i at tabelltypen gir det mening å få det med for å gjøre livet lettere for brukeren

2024-07-12 09:36 UTC, SondreKanstad commented on backend/src/main/kotlin/no/bekk/model/internal/Question.kt
> +    val comments: List<Comment>? = null,
Tenker at answers og comments ikke burde være nullable siden det er lister, så kan heller være en tom liste? 🤔 Ellers burde begge være nullable

2024-07-12 09:36 UTC, SondreKanstad approved these changes

2024-07-12 11:08 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +fun Route.tableRouting() {
Should this be in its separate file or does it make sense to keep as is?

2024-07-12 11:11 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +    suspend fun getTableFromAirTable(tableId: String, team: String?): Table {
Kan team noensinne bli noe annet en string? Vi thrower error på linje 19

2024-07-12 11:12 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +        val comments = getComments(team)
Hvis tema ikke kan vare null blir det kanske endringer her i tillegg

2024-07-12 11:15 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +            columns = fields,
I think we should try to decide on 1 name for all parts of the data and use that throughout the whole project. Here we are saying that columns === fields so why not call both fields or columns everywhere to avoid confusion

2024-07-12 11:16 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +    metadataFields: List<Field>,
```suggestion
    metaDataFields: List<Field>,
```

2024-07-12 11:18 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +    suspend fun getTableFromAirTable(tableId: String, team: String?): Table {
Vi thrower bare på tableId med mindre eg ser feil? Så team kan være `null`

2024-07-12 11:19 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +            columns = fields,
Agree! Any preferences? I like column in a table reference, but for a question I find fields more fitting

2024-07-12 11:20 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +fun Route.tableRouting() {
Yeah not sure how to handle this. Do we want a routing folder for all the different routes perhaps?

2024-07-12 11:20 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +        id = fields.jsonObject["ID"]?.jsonPrimitive?.content ?: "",
Should it be possible to map a question with an empty string as ID?

2024-07-12 11:27 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/domain/MetodeverkResponse.kt
> +        id = fields.jsonObject["ID"]?.jsonPrimitive?.content ?: "",
maybe create a uuid or something instead

2024-07-12 11:30 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/model/airtable/AirtableMapping.kt
> +    return when (airtableFieldType) {
Create a enum for this perhaps?

2024-07-12 11:36 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/model/internal/Question.kt
> +    val comments: List<Comment>? = null,
Enig!

2024-07-12 11:39 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/QuestionController.kt
> +fun Route.questionRouting() {
Think I mentioned this in the tableRouting: But perhaps this should be in its own directory just for routes so you have routes, services an controllers separated

2024-07-12 11:40 UTC, perzonas requested changes
Very good work. I think this is really comming along

2024-07-12 13:21 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/controllers/TableController.kt
> +        }
Laget kort på!

2024-07-12 13:50 UTC, perzonas commented on backend/src/main/kotlin/no/bekk/controllers/QuestionController.kt
> +    fun getTestQuestions(): List<Question> {
should we havea function for getting non test Question or is that just the airTable stuff perhaps?

2024-07-12 13:51 UTC, perzonas approved these changes
Really great work!

2024-07-12 13:53 UTC, KrisAesoey commented on backend/src/main/kotlin/no/bekk/controllers/QuestionController.kt
> +    fun getTestQuestions(): List<Question> {
Per now I felt that this made sense just because we don't have any other data sources to use. Like, we could have an endpoint you convert the JSON to and it would just map and spit it out the same way. But, I don't see the value just yet.

2024-07-12 13:53 UTC, merged